#property copyright "Generated by GPT-5 Codex"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

enum OscillatorType
{
   OSC_RSI = 0,
   OSC_STOCHASTIC,
   OSC_STOCH_RSI,
   OSC_MFI
};

//--- Inputs
input double          InpLots             = 0.10;       // Lot size
input int             InpLength           = 150;        // LogReg lookback
input double          InpChannelWidth     = 1.5;        // Channel width (stdev multiplier)
input double          InpProximityPct     = 5.0;        // Boundary proximity (%)
input OscillatorType  InpOscillator       = OSC_RSI;    // Oscillator selection
input int             InpOscLength        = 14;         // Oscillator length
input int             InpSignalLength     = 14;         // Signal smoothing length
input bool            InpRequireTrend     = true;       // Require trend agreement
input double          InpStopLossPoints   = 0.0;        // Stop-loss (points)
input double          InpTakeProfitPoints = 0.0;        // Take-profit (points)
input uint            InpMagic            = 460015;     // Magic number
input uint            InpSlippage         = 10;         // Slippage (points)

CTrade trade;

datetime g_lastBarTime = 0;

//--- Utility functions ---------------------------------------------------------
bool CalcLogRegression(const double &price[], int shift, int len, int total, double &regMid, double &stdDeviation)
{
   if(shift + len > total)
      return false;

   double sumX = 0.0;
   double sumY = 0.0;
   double sumXSq = 0.0;
   double sumXY = 0.0;
   int i;

   for(i = 0; i < len; ++i)
   {
      double val = price[shift + i];
      if(val <= 0.0)
         return false;

      double logVal = MathLog(val);
      double per = i + 1.0;

      sumX   += per;
      sumY   += logVal;
      sumXSq += per * per;
      sumXY  += per * logVal;
   }

   double denom = len * sumXSq - sumX * sumX;
   if(MathAbs(denom) < DBL_EPSILON)
      return false;

   double slope = (len * sumXY - sumX * sumY) / denom;
   double intercept = (sumY - slope * sumX) / len;

   regMid = MathExp(intercept);

   // Standard deviation of prices (not logs) over the window
   double mean = 0.0;
   for(i = 0; i < len; ++i)
      mean += price[shift + i];
   mean /= len;

   double variance = 0.0;
   for(i = 0; i < len; ++i)
   {
      double diff = price[shift + i] - mean;
      variance += diff * diff;
   }
   variance /= len;
   stdDeviation = MathSqrt(variance);

   return MathIsValidNumber(regMid) && MathIsValidNumber(stdDeviation);
}

double CalcRSI(const double &price[], int shift, int len, int total)
{
   if(shift + len + 1 > total)
      return 50.0;

   double gain = 0.0;
   double loss = 0.0;
   int i;

   for(i = 0; i < len; ++i)
   {
      double diff = price[shift + i] - price[shift + i + 1];
      if(diff > 0.0)
         gain += diff;
      else
         loss -= diff;
   }

   double avgGain = gain / len;
   double avgLoss = loss / len;

   if(avgLoss == 0.0)
      return 100.0;

   double rs = avgGain / avgLoss;
   return 100.0 - (100.0 / (1.0 + rs));
}

double CalcStochastic(const double &close[], const double &high[], const double &low[], int shift, int len, int total)
{
   if(shift + len > total)
      return 50.0;

   double highest = -DBL_MAX;
   double lowest  = DBL_MAX;
   int i;

   for(i = 0; i < len; ++i)
   {
      highest = MathMax(highest, high[shift + i]);
      lowest  = MathMin(lowest,  low[shift + i]);
   }

   if(MathAbs(highest - lowest) < DBL_EPSILON)
      return 50.0;

   return (close[shift] - lowest) / (highest - lowest) * 100.0;
}

double CalcMFI(const double &high[], const double &low[], const double &close[], const long &volume[], int shift, int len, int total)
{
   if(shift + len + 1 > total)
      return 50.0;

   double posFlow = 0.0;
   double negFlow = 0.0;
   int i;

   for(i = 0; i < len; ++i)
   {
      int idx = shift + i;
      double typical     = (high[idx] + low[idx] + close[idx]) / 3.0;
      double typicalPrev = (high[idx + 1] + low[idx + 1] + close[idx + 1]) / 3.0;
      double flow = typical * (double)volume[idx];

      if(typical >= typicalPrev)
         posFlow += flow;
      else
         negFlow += flow;
   }

   if(negFlow == 0.0)
      return 100.0;

   double ratio = posFlow / negFlow;
   return 100.0 - (100.0 / (1.0 + ratio));
}

double CalcStochasticRSI(const double &price[], int shift, int len, int total)
{
   if(shift + len + 1 > total)
      return 50.0;

   double highest = -DBL_MAX;
   double lowest  = DBL_MAX;
   int i;

   for(i = 0; i < len; ++i)
   {
      double rsiVal = CalcRSI(price, shift + i, len, total);
      highest = MathMax(highest, rsiVal);
      lowest  = MathMin(lowest,  rsiVal);
   }

   if(MathAbs(highest - lowest) < DBL_EPSILON)
      return 50.0;

   double current = CalcRSI(price, shift, len, total);
   return (current - lowest) / (highest - lowest) * 100.0;
}

double GetOscillatorValue(const double &close[], const double &high[], const double &low[], const long &volume[], int total, int shift)
{
   switch(InpOscillator)
   {
      case OSC_RSI:
         return CalcRSI(close, shift, InpOscLength, total);

      case OSC_STOCHASTIC:
         return CalcStochastic(close, high, low, shift, InpOscLength, total);

      case OSC_STOCH_RSI:
         return CalcStochasticRSI(close, shift, InpOscLength, total);

      case OSC_MFI:
         return CalcMFI(high, low, close, volume, shift, InpOscLength, total);
   }

   return 50.0;
}

void CloseOppositePositions(bool wantBuy)
{
   int idx;
   for(idx = PositionsTotal() - 1; idx >= 0; --idx)
   {
      if(!PositionSelectByIndex(idx))
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != (long)InpMagic)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;

      long type = PositionGetInteger(POSITION_TYPE);
      if((wantBuy && type == POSITION_TYPE_SELL) || (!wantBuy && type == POSITION_TYPE_BUY))
         trade.PositionClose(_Symbol);
   }
}

bool HasPosition(bool wantBuy)
{
   int idx;
   for(idx = PositionsTotal() - 1; idx >= 0; --idx)
   {
      if(!PositionSelectByIndex(idx))
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != (long)InpMagic)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;

      long type = PositionGetInteger(POSITION_TYPE);
      if((wantBuy && type == POSITION_TYPE_BUY) || (!wantBuy && type == POSITION_TYPE_SELL))
         return true;
   }
   return false;
}

void OpenTrade(bool isBuy)
{
   if(HasPosition(isBuy))
      return;

   CloseOppositePositions(isBuy);

   double price = isBuy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double sl = 0.0, tp = 0.0;

   if(InpStopLossPoints > 0.0)
      sl = isBuy ? price - InpStopLossPoints * point : price + InpStopLossPoints * point;
   if(InpTakeProfitPoints > 0.0)
      tp = isBuy ? price + InpTakeProfitPoints * point : price - InpTakeProfitPoints * point;

   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints((int)InpSlippage);

   bool result = isBuy ? trade.Buy(InpLots, _Symbol, price, sl, tp) : trade.Sell(InpLots, _Symbol, price, sl, tp);
   if(!result)
      PrintFormat("OrderSend error %d", GetLastError());
}

bool EvaluateSignals(bool &longSignal, bool &shortSignal)
{
   int needed = MathMax(InpLength, InpOscLength * 2) + 10;

   double closeArr[]; ArraySetAsSeries(closeArr, true);
   double highArr[];  ArraySetAsSeries(highArr, true);
   double lowArr[];   ArraySetAsSeries(lowArr, true);
   long   volumeArr[];ArraySetAsSeries(volumeArr, true);

   int copiedClose = CopyClose(_Symbol, _Period, 0, needed, closeArr);
   int copiedHigh  = CopyHigh(_Symbol, _Period, 0, needed, highArr);
   int copiedLow   = CopyLow(_Symbol, _Period, 0, needed, lowArr);
   int copiedVol   = CopyTickVolume(_Symbol, _Period, 0, needed, volumeArr);

   if(copiedClose < InpLength + 3 || copiedHigh < InpLength + 3 || copiedLow < InpLength + 3)
      return false;

   double regMidCurr = 0.0, regMidPrev = 0.0;
   double stdCurr = 0.0, stdPrev = 0.0;

   if(!CalcLogRegression(closeArr, 1, InpLength, copiedClose, regMidCurr, stdCurr))
      return false;
   if(!CalcLogRegression(closeArr, 2, InpLength, copiedClose, regMidPrev, stdPrev))
      return false;

   double channelHalf = stdCurr * InpChannelWidth;
   double upper = regMidCurr + channelHalf;
   double lower = regMidCurr - channelHalf;
   double range = upper - lower;
   double proximity = range * InpProximityPct / 100.0;

   double closePrice = closeArr[1];
   bool nearLower = closePrice <= lower + proximity;
   bool nearUpper = closePrice >= upper - proximity;

   if(copiedVol < InpOscLength + InpSignalLength + 2 || copiedClose < InpOscLength + InpSignalLength + 3)
      return false;

   int smoothLen = MathMax(InpSignalLength, 1);
   double sumCurr = 0.0;
   double sumPrev = 0.0;
   int i;

   for(i = 0; i < smoothLen; ++i)
   {
      double valCurr = GetOscillatorValue(closeArr, highArr, lowArr, volumeArr, copiedClose, 1 + i);
      double valPrev = GetOscillatorValue(closeArr, highArr, lowArr, volumeArr, copiedClose, 2 + i);
      sumCurr += valCurr;
      sumPrev += valPrev;
   }

   double oscCurr = sumCurr / smoothLen;
   double oscPrev = sumPrev / smoothLen;

   if(!MathIsValidNumber(oscCurr) || !MathIsValidNumber(oscPrev))
      return false;

   bool crossUp = (oscPrev < 50.0 && oscCurr >= 50.0);
   bool crossDown = (oscPrev > 50.0 && oscCurr <= 50.0);

   double trendSlope = regMidCurr - regMidPrev;

   longSignal  = nearLower && crossUp   && (!InpRequireTrend || trendSlope > 0.0);
   shortSignal = nearUpper && crossDown && (!InpRequireTrend || trendSlope < 0.0);

   return true;
}

int OnInit()
{
   trade.SetExpertMagicNumber(InpMagic);
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   // Optional cleanup
}

void OnTick()
{
   datetime currentBar = iTime(_Symbol, _Period, 0);
   if(currentBar == g_lastBarTime)
      return;
   g_lastBarTime = currentBar;

   bool longSignal = false, shortSignal = false;
   if(!EvaluateSignals(longSignal, shortSignal))
      return;

   if(longSignal)
      OpenTrade(true);
   else if(shortSignal)
      OpenTrade(false);
}

